name: Keep HF Space Alive
on:
  schedule:
    - cron: "0 0 */1 * *"   # runs once every day
  workflow_dispatch:        # allows manual trigger
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Space
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://manuagr03-career-conversation.hf.space/
          curl -s -o /dev/null -w "%{http_code}" https://manuagr03-deep-research.hf.space/
          curl -s -o /dev/null -w "%{http_code}" https://manuagr03-medical.hf.space/
          curl -s -o /dev/null -w "%{http_code}" https://manuagr03-career-agent.hf.space
