name: Trigger Make Webhook

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'   # 06:00 IST
    - cron: '30 4 * * *'   # 10:00 IST
    - cron: '10 13 * * *'  # 20:00 IST
    - cron: '10 14 * * *'  # 21:00 IST

jobs:
  call-make:
    runs-on: ubuntu-latest
    steps:
      - name: Determine slot and call Make webhook
        run: |
          hour=$(date +'%H')
          case "$hour" in
            0) SLOT="morning" ;;
            4) SLOT="midday" ;;
            13) SLOT="evening" ;;
            14) SLOT="night" ;;
            *) SLOT="unknown" ;;
          esac

          if [ "$SLOT" != "unknown" ]; then
            echo "Determined slot: $SLOT"
            curl -X POST -H "Content-Type: application/json" \
                 -d "{\"slot\":\"$SLOT\"}" \
                 "${{ secrets.DIET_PLAN_AUTOMATOR }}"
          else
            echo "No slot to send for hour $hour"
          fi
