name: Trigger Make Webhook

on:
#  workflow_dispatch:       # allows manual run
#    inputs:
#      slot:
#        description: 'Slot to trigger manually (morning, midday, evening, night)'
#        required: false
  schedule:
    - cron: '30 0 * * *'   # 06:00 IST
    - cron: '30 4 * * *'   # 10:00 IST
    - cron: '23 11 * * *'  # 20:00 IST
    - cron: '26 11 * * *'  # 21:00 IST

jobs:
  call-make:
    runs-on: ubuntu-latest
    steps:
 #     - name: Determine slot
 #       id: slot
 #       run: |
 #         if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.slot }}" ]; then
 #           SLOT="${{ github.event.inputs.slot }}"
 #         else
 #           hour=$(date +'%H')
 #           case "$hour" in
 #             0) SLOT="morning" ;;
 #             4) SLOT="midday" ;;
 #             14) SLOT="evening" ;;
 #             15) SLOT="night" ;;
 #             *) SLOT="unknown" ;;
 #           esac
 #         fi
 #         echo "slot=$SLOT" >> $GITHUB_OUTPUT
 #         echo "Determined slot: $SLOT"

 #     - name: Call Make webhook
 #       if: steps.slot.outputs.slot != 'unknown'
 #       run: |
 #         curl -X POST -H "Content-Type: application/json" \
 #              -d "{\"slot\":\"${{ steps.slot.outputs.slot }}\"}" \
 #              "${{ secrets.DIET_PLAN_AUTOMATOR }}"
               
      - name: Determine slot and call Make webhook
        run: |
          hour=$(date +'%H')
          case "$hour" in
            0) SLOT="morning" ;;
            4) SLOT="midday" ;;
            14) SLOT="evening" ;;
            15) SLOT="night" ;;
            *) SLOT="unknown" ;;
          esac

          if [ "$SLOT" != "unknown" ]; then
            echo "Determined slot: $SLOT"
            curl -X POST -H "Content-Type: application/json" \
                 -d "{\"slot\":\"$SLOT\"}" \
                 "${{ secrets.DIET_PLAN_AUTOMATOR }}"
          else
            echo "No slot to send for hour $hour"
          fi
#      - name: Send morning slot (06:00 IST)
#        if: github.event.schedule == '30 0 * * *'
#        run: |
#          curl -X POST -H "Content-Type: application/json" \
#          -d '{"slot":"morning"}' \
#          "${{ secrets.DIET_PLAN_AUTOMATOR }}"

#      - name: Send midday slot (10:00 IST)
#        if: github.event.schedule == '30 4 * * *'
#        run: |
#          curl -X POST -H "Content-Type: application/json" \
#          -d '{"slot":"midday"}' \
#          "${{ secrets.DIET_PLAN_AUTOMATOR }}"

#      - name: Send evening slot (20:00 IST)
#        if: github.event.schedule == '30 14 * * *'
#         run: |
#         curl -X POST -H "Content-Type: application/json" \
#          -d '{"slot":"evening"}' \
#          "${{ secrets.DIET_PLAN_AUTOMATOR }}"

#      - name: Send night slot (21:00 IST)
#        if: github.event.schedule == '30 15 * * *'
#        run: |
#          curl -X POST -H "Content-Type: application/json" \
#          -d '{"slot":"night"}' \
#          "${{ secrets.DIET_PLAN_AUTOMATOR }}"
