name: Trigger Make Webhook

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'   # 06:00 IST
    - cron: '30 4 * * *'   # 10:00 IST
    - cron: '30 14 * * *'  # 20:00 IST
    - cron: '30 16 * * *'  # 21:00 IST

jobs:
  call-make:
    runs-on: ubuntu-latest
    steps:
      - name: Determine slot and call Make webhook
        run: |
          if [[ "${{ github.event.schedule }}" == "30 0 * * *" ]]; then
            SLOT="morning"
          elif [[ "${{ github.event.schedule }}" == "30 4 * * *" ]]; then
            SLOT="midday"
          elif [[ "${{ github.event.schedule }}" == "30 14 * * *" ]]; then
            SLOT="evening"
          elif [[ "${{ github.event.schedule }}" == "30 16 * * *" ]]; then
            SLOT="night"
          else
            SLOT="unknown"
          fi

          echo "Determined slot: $SLOT"

          if [ "$SLOT" != "unknown" ]; then
            curl -X POST -H "Content-Type: application/json" \
                 -d "{\"slot\":\"$SLOT\"}" \
                 "${{ secrets.DIET_PLAN_AUTOMATOR }}"
          else
            echo "Skipping webhook call because slot is unknown"
          fi
