name: Trigger Make Webhook

on:
  workflow_dispatch:       # allows manual run
  schedule:
    - cron: '30 0 * * *'   # 06:00 IST
    - cron: '30 4 * * *'   # 10:00 IST
    - cron: '30 14 * * *'  # 20:00 IST
    - cron: '30 15 * * *'  # 21:00 IST

jobs:
  call-make:
    runs-on: ubuntu-latest
    steps:
      - name: Send morning slot (06:00 IST)
        if: github.event.schedule == '30 0 * * *'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"slot":"morning"}' \
          "${{ secrets.DIET_PLAN_AUTOMATOR }}"

      - name: Send midday slot (10:00 IST)
        if: github.event.schedule == '30 4 * * *'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"slot":"midday"}' \
          "${{ secrets.DIET_PLAN_AUTOMATOR }}"

      - name: Send evening slot (20:00 IST)
        if: github.event.schedule == '30 14 * * *'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"slot":"evening"}' \
          "${{ secrets.DIET_PLAN_AUTOMATOR }}"

      - name: Send night slot (21:00 IST)
        if: github.event.schedule == '30 15 * * *'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"slot":"night"}' \
          "${{ secrets.DIET_PLAN_AUTOMATOR }}"
